export type UserData = {
  rank: number,
  id: number,
  key: string,
  name: string,
  preKvkPower: number,
  currentPower: number | string,
  preKvkDead: number,
  currentDead: number | string,
  totalT4Dead: number | string,
  totalT5Dead: number | string,
  preKvkKillPoints: number,
  currentKillPoints: number | string,
  preKvkT4KillPoints: number,
  currentT4KillPoints: number | string,
  preKvkT5KillPoints: number,
  currentT5KillPoints: number | string,
  isZeroed: boolean,
  isMigrated: boolean,
  kpi: number,
  require_kpi: number
}