export type UserData = {
  rank: number,
  id: number,
  name: string,
  preKvkPower: number,
  currentPower: number,
  preKvkDead: number,
  currentDead: number,
  totalT4Dead: number,
  totalT5Dead: number,
  preKvkKillPoints: number,
  currentKillPoints: number,
  preKvkT4KillPoints: number,
  currentT4KillPoints: number,
  preKvkT5KillPoints: number,
  currentT5KillPoints: number,
  isZeroed: boolean,
  isMigrated: boolean,
  kpi: number,
  require_kpi: number
}