import Sidebar from "@/components/Sidebar";
import "./globals.css";
import "./common.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "KINGDOM 2832 - KVK 5",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div>
          {children}
          <Sidebar />
        </div>
      </body>
    </html>
  );
}
